services:
  smf-app:
    image: ezerous/php-5.3.29-apache-2
    container_name: smf_app
    ports:
      - "6789:80"
    volumes:
      - ./volumes/smf_app_volume:/var/www/html
    networks:
      - smf-network
    restart: unless-stopped

  smf_db:
    image: ezerous/mysql-5.1.73
    container_name: smf_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/smf_db_volume:/var/lib/mysql
    networks:
      - smf-network
    restart: unless-stopped

networks:
  smf-network:
    driver: bridge
