services:
  smf-app:
    image: ezerous/php-apache:5.4-latest
    container_name: smf_app
    ports:
      - "127.0.0.1:6789:80"
    volumes:
      - ./volumes/smf_app_volume:/var/www/html
    networks:
      - smf-network
    restart: unless-stopped

  smf_db:
    image: ezerous/mysql:5.1-latest
    container_name: smf_db
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/smf_db_volume:/var/lib/mysql
    networks:
      - smf-network
    restart: unless-stopped

  smf_adminer:
    image: adminer
    container_name: smf_adminer
    ports:
      - "127.0.0.1:3307:8080"
    environment:
      ADMINER_DEFAULT_SERVER: smf_db
    networks:
      - smf-network
    restart: unless-stopped

networks:
  smf-network:
    driver: bridge
